name: Build Picture Element Editor

on:
  push:
    branches: [main]
    paths:
      - 'ha-picture-element-editor-addon/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ha-picture-element-editor-addon
          file: ./ha-picture-element-editor-addon/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha-picture-element-editor:latest
            ghcr.io/${{ github.repository_owner }}/ha-picture-element-editor:${{ github.sha }} 